[phases.setup]
nixPkgs = ["php81", "composer", "php81Extensions.pdo_mysql", "php81Extensions.mbstring", "php81Extensions.tokenizer"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=8080"
