name: Laravel CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: StratDefOps
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Cache Composer Dependencies
      uses: actions/cache@v3
      with:
        path: backend/vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, bcmath, pdo, pdo_mysql

    - name: Copy .env
      run: cp backend/.env.example backend/.env

    - name: Install Dependencies
      run: |
        cd backend
        composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Generate Application Key
      run: |
        cd backend
        php artisan key:generate

    - name: Set Directory Permissions
      run: sudo chmod -R 777 backend/storage backend/bootstrap/cache

    - name: Wait for MySQL to be ready
      run: |
        until mysqladmin ping -h 127.0.0.1 -u root -proot --silent; do
          echo "Waiting for MySQL to be ready..."
          sleep 2
        done

    - name: Import Database Schema and Data
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: StratDefOps
        DB_USERNAME: root
        DB_PASSWORD: root
      run: |
        mysql -h 127.0.0.1 -u root -proot StratDefOps < backend/database/migrations/001_init_tables.sql
        mysql -h 127.0.0.1 -u root -proot StratDefOps < backend/database/seeders/seed_data.sql

    - name: Cache Configuration
      run: |
        cd backend
        php artisan config:cache

    - name: Run Tests (Unit & Feature)
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: StratDefOps
        DB_USERNAME: root
        DB_PASSWORD: root
      run: |
        cd backend
        php artisan test
